ProjectManagement/ProjectManagementLayer/Controllers/Api/TasksController.cs
using AutoMapper;
using BusinessLogic;
using ProjectManagementLayer.DTO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace ProjectManagementLayer.Controllers.Api
{
    public class TasksController : ApiController
    {
        private IMapper mapper;
        private ILogic _context;

        public TasksController()
        {
            mapper = DTO.AutoMapperConfig.GetMapper();
            _context = new RealLogic();
        }

        //GET /api/tasks
        [HttpGet]
        public IEnumerable<TaskDto> GetTasks()
        {
            return _context.GetTasks().ToList().Select(mapper.Map<Data.TASKS, DTO.TaskDto>);
        }

        [Route("api/tasks/admin")]
        [HttpGet]
        public IEnumerable<TaskDto> GetAdminTasks()
        {
            return _context.GetTasks().Where(t => t.TISDONE == false).Select(mapper.Map<Data.TASKS, DTO.TaskDto>).ToList();
        }

        [Route("api/tasks/gettask/{id}")]
        // GET /api/tasks/1
        public IHttpActionResult GetTask(int id)
        {
            var task = _context.GetOneTask(id);

            if (task == null)
                return NotFound();

            return Ok(mapper.Map<Data.TASKS, TaskDto>(task));
        }

        [HttpGet]
        public IEnumerable<TaskDto> GetTasksForProject(int id)
        {
            var tasks = _context.GetTasks().Where(task => task.T_PID == id  && task.TISDONE == false).Select(mapper.Map<Data.TASKS, DTO.TaskDto>);

            return tasks;
        }

        // POST /api/tasks
        [HttpPost]
        public IHttpActionResult CreateTask(TaskDto taskDto)
        {
            //addolni a getnextid() metódust?
            if (!ModelState.IsValid)
                return BadRequest();

            var task = mapper.Map<TaskDto, Data.TASKS>(taskDto);
            _context.AddTask(task);

            taskDto.TId = task.TID;
            return Created(new Uri(Request.RequestUri + "/" + task.TID), taskDto);
        }

        // PUT /api/tasks/1
        [HttpPut]
        public void UpdateTask(int id, TaskDto taskDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var taskInDb = _context.GetOneTask(id);

            if (taskInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            mapper.Map(taskDto, taskInDb);
            //kell egy olyan ilogic ami modositáskor egész projectet fogad 
            _context.ModifyTask(taskInDb.TID, taskInDb.TNAME, taskInDb.TISDONE, taskInDb.TISARCHIVED, taskInDb.TISPINNED, (float)taskInDb.TEXPENSES, taskInDb.TCOMMENT, (int)taskInDb.TREQUIREMENT);
        }

        [Route("api/tasks/modifyuser")]
        [HttpPut]
        public void UpdateUserForTask(TaskDto taskDto)
        {
            var taskInDb = _context.GetOneTask(taskDto.TId);

            if (taskInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.ModifyUserIDInTask(taskDto.TId, taskDto.T_UId);
        }

        // DELETE /api/projects/1
        [HttpDelete]
        public IHttpActionResult DeleteTask(int id)
        {
            var taskInDb = _context.GetOneTask(id);

            if (taskInDb == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            _context.DelTask(id);
            return Ok("ok");
        }

        //[Route("api/tasks/isdone/{id}/{name}")]
        [HttpGet]
        public IHttpActionResult AddTaskToDone(int id, string name)
        {
            var userId = _context.GetUsers().Single(u => u.UNAME == name).UID;
            var taskList = _context.GetTasks().Where(t => t.TISDONE == true && t.T_UID == userId).Select(mapper.Map<Data.TASKS, DTO.TaskDto>).ToList();
            return Ok(taskList);
        }

        [Route("api/tasks/isdone/{id}")]
        [HttpGet]
        public IHttpActionResult AddTaskToDone(int id)
        {
            var taskInDb = _context.GetOneTask(id);
            if (taskInDb.TISDONE == true)
                return BadRequest("Már hozzá volt adva!");
            if(taskInDb.TREQUIREMENT.HasValue)
            {
                var taskReq = _context.GetOneTask(taskInDb.TREQUIREMENT.Value);
                if (taskReq.TISDONE == false)
                    return BadRequest("Nincs kész az előfeltétele!");
            }
            taskInDb.TISDONE = true;
            _context.ModifyTasK(taskInDb);
            return Ok("Sikeres módositás!");
        }
    }
}

ProjectManagement/ProjectManagementLayer/Controllers/TaskController.cs
using AutoMapper;
using BusinessLogic;
using ProjectManagementLayer.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectManagementLayer.Controllers
{
    public class TaskController : Controller
    {
        private IMapper mapper;
        private ILogic _context;

        public TaskController()
        {
            mapper = DTO.AutoMapperConfig.GetMapper();
            _context = new RealLogic();
        }

        public ActionResult Index(int id)
        {
            var viewModel = new TaskIndexViewModel
            {
                ProjectId = id,
                UserModel = _context.GetUsers().Select(mapper.Map<Data.USERS, Models.UserModel>).Single(u => u.UName == User.Identity.Name)
            };
            return View(viewModel);
        }

        [Authorize(Roles = "Manager")]
        public ActionResult Admin()
        {
            var users = _context.GetUsers().Select(mapper.Map<Data.USERS, Models.UserModel>).ToList();
            return View(users);
        }

        public ActionResult Edit(int id)
        {
            ViewBag.Name = "Edit Task";

            var task = _context.GetOneTask(id);

            if (task == null)
                return HttpNotFound();
            var projects = _context.GetProjects().ToList();
            var taskList = _context.GetTasks().Select(mapper.Map<Data.TASKS, Models.TaskModel>).ToList();
            var viewModel = new TaskFormViewModel
            {
                TaskModel = mapper.Map<Data.TASKS, Models.TaskModel>(task),
                ProjectModels = mapper.Map<List<Data.PROJECTS>, List<Models.ProjectModel>>(projects),
                TaskList = taskList
            };
            return View("TaskForm", viewModel);
        }

        public ActionResult New(int id)
        {
            ViewBag.Name = "Create new Task";
            var projects = _context.GetProjects().ToList();
            var taskList = _context.GetTasks().ToList();
            //var groupsList = mapper.Map<List<Data.GROUPS>, List<DTO.Group>>(groups);
            var newTaskViewModel = new TaskFormViewModel
            {
                TaskModel = new Models.TaskModel() { T_PId = id},
                ProjectModels = mapper.Map<List<Data.PROJECTS>, List<Models.ProjectModel>>(projects),
                TaskList = mapper.Map<List<Data.TASKS>, List<Models.TaskModel>>(taskList)
            };
            return View("TaskForm", newTaskViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Models.TaskModel taskModel)
        {
            if (!ModelState.IsValid)
            {
                var viewModel = new TaskFormViewModel
                {
                    TaskModel = taskModel,
                    ProjectModels = mapper.Map<List<Data.PROJECTS>, List<Models.ProjectModel>>(_context.GetProjects().ToList()),
                    TaskList = mapper.Map<List<Data.TASKS>, List<Models.TaskModel>>(_context.GetTasks().ToList())
                };
                return View("TaskForm", viewModel);
            }
            if (taskModel.TId == 0)
            {
                taskModel.TId = _context.GetNextTaskId();
                taskModel.T_UId = _context.GetUsers().Single(u => u.UNAME == User.Identity.Name).UID;
                var task = mapper.Map<Models.TaskModel, Data.TASKS>(taskModel);
                _context.AddTask(task);
            }
            else
            {
                var taskInDb = _context.GetOneTask(taskModel.TId);
                mapper.Map(taskModel, taskInDb);
                _context.ModifyTasK(taskInDb);
            }

            return RedirectToAction("Index", "Home");
        }

        public ActionResult Details(int id)
        {
            var task = _context.GetOneTask(id);
            var taskModel = mapper.Map<Data.TASKS, Models.TaskModel>(task);
            Data.TASKS requiredTask = null;
            if (task.TREQUIREMENT != null)
                requiredTask = _context.GetOneTask(task.TREQUIREMENT.Value);

            var viewModel = new TaskDetailsViewModel
            {
                TaskModel = taskModel,
                RequiredTask = mapper.Map<Data.TASKS, Models.TaskModel>(requiredTask)
            };

            if (viewModel == null)
                return HttpNotFound();

            return View(viewModel);
        }
    }
}

ProjectManagement/ProjectManagementLayer/Views/Task/Admin.cshtml
@model List<ProjectManagementLayer.Models.UserModel>
@{
	ViewBag.Title = "All Tasks";
}

<h2>Felvett Taskok</h2><br />
<table id="tasks" class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Task Name</th>
			<th>Description</th>
			<th>User</th>
			<th>Details</th>
		</tr>
	</thead>
	<tbody></tbody>
</table>

@section scripts
{
	<script>
		$(document).ready(function () {
			var table = $("#tasks").DataTable({
				ajax: {
					url: "/api/tasks/admin" ,
					method: "GET",
					dataSrc: ""
				},
				columns: [
					{
						data: "tName"
					},
					{
						data: "tComment"
					},
					{
						data: "t_uId" ,
						render: function (data, type, task) {
							return "<button class='btn-link js-user' data-project-id=" + data + ">User</button>";
						}
					},
					{
						data: "tId",
						render: function (data) {
							return "<button class='btn-link js-details' data-project-id=" + data + ">Details</button>";
						}
					}
				]
			});

			$("#tasks").on("click", ".js-delete", function () {
				var button = $(this);

				bootbox.confirm("Are you sure to delete this project?", function (result) {
					if (result) {
						$.ajax({
							url: "/api/tasks/" + button.attr("data-project-id"),
							method: "DELETE",
							success: function () {
								table.row(button.closest("tr")).remove().draw();
							}
						});
					}
				});
			});

			$("#tasks").on("click", ".js-details", function () {
				var button = $(this);
				window.location.href = ("/Task/Details/" + button.attr("data-project-id"))
			});

			$("#tasks").on("click", ".js-user", function () {
				var button = $(this);
				window.location.href = ("/User/Details/" + button.attr("data-project-id"))
			});

			$("#tasks").on("click", ".js-add", function () {
				var button = $(this);
				bootbox.confirm("Are you sure to add this project?", function (result) {
					if (result) {
						$.ajax({
							url: "/api/tasks/gettask/" + button.attr("data-project-id"),
							method: "GET",
							success: function (task) {
								alert("Sikeres lekérés");
								$.ajax({
									url: "/api/tasks/modifyuser",
									method: "PUT",
									data: {tId : task.tId, t_uId : 10},
									success: function () {
										bootbox.alert("Sikeres modositás");
									}
								});
							}
						}).done(function () {
							$.ajax({
								url: "/api/tasks/gettask/" + button.attr("data-project-id"),
								method: "GET",
								success: function (gettask) {
									bootbox.alert("Az új userId: " + gettask.t_uId);
								}
							});
						});
					}
				});
			});
		});
	</script>
}

ProjectManagement/ProjectManagementLayer/Views/Task/Details.cshtml
@model ProjectManagementLayer.ViewModels.TaskDetailsViewModel
@{
    ViewBag.Title = "Details";
}

<h3>@Model.TaskModel.TName</h3>
<ul>
    @if (@Model.TaskModel.TIsArchived)
    {
        <li><strong>A task archivált.</strong></li> }
    @if (@Model.TaskModel.TIsDone)
    {
        <li><strong>A task kész van.</strong></li> }
    <li>A taskhoz tartozó projekt: @Model.TaskModel.T_PId</li>
    <li>A task leirása leirása: @Model.TaskModel.TComment</li>
    @if (Model.RequiredTask != null)
    {
        <li>A task előfeltétele: @Html.ActionLink(@Model.RequiredTask.TName, "Details", "Task", new { id = Model.RequiredTask.TId }, null)</li>
    }
    else
    {
        <li>A tasknak nincsen előfeltétele.</li>
    }
</ul>

ProjectManagement/ProjectManagementLayer/Views/Task/Index.cshtml
@model ProjectManagementLayer.ViewModels.TaskIndexViewModel
@{
	ViewBag.Title = "Available Tasks";
}

<h2>Felvehető Taskok</h2><br />
<table id="tasks" class="table table-bordered table-hover">
	<thead>
		<tr>
			<th>Task Name</th>
			<th>Description</th>
			<th>Add</th>
			<th>Details</th>
			<th>Delete</th>
            <th>Felvett</th>
		</tr>
	</thead>
	<tbody></tbody>
</table>
<form action="http://localhost:1801/Task/New/@Model.ProjectId/"><input type="submit" value="Add new Task" /></form><br />
<checkbox></checkbox>

@section scripts
{
	<script>
        $(document).ready(function () {
            var table = $("#tasks").DataTable({
                ajax: {
                    url: "/api/tasks/" + @Model.ProjectId ,
                    method: "GET",
                    dataSrc: ""
                },
                columns: [
					{
					    data: "tName",
					    render: function (data, type, task) {
					        return "<a href='/Task/Edit/" + task.tId + "'>" + task.tName + "</a>";
					    }
					},
					{
					    data: "tComment"
					},
					{
					    data: "tId",
					    render: function (data) {
					        return "<button class='btn-link js-add' data-project-id=" + data + ">Add</button>";
					    }
					},
					{
					    data: "tId",
					    render: function (data) {
					        return "<button class='btn-link js-details' data-project-id=" + data + ">Details</button>";
					    }
					},
					{
					    data: "tId",
					    render: function (data) {
					        return "<button class='btn-link js-delete' data-project-id=" + data + ">Delete</button>";
					    }
					},
                    {
                        data: "t_uId",
                        render: function ( data, type, user ) {
                            if ( user != null ) {
                                return '<input type="checkbox" id="AssignedUser" class="editor-active js-check" checked>';
                            }
                            return '<input type="checkbox" class="editor-inaktiv">';
                        }
                    }
                ],
            });

            $("#tasks").on("change", ".js-check" ,function() {
                if(this.checked) {
                    bootbox.alert("VÁltozásss!!!");
                }
            });

			$("#tasks").on("click", ".js-delete", function () {
				var button = $(this);

				bootbox.confirm("Are you sure to delete this project?", function (result) {
					if (result) {
						$.ajax({
							url: "/api/tasks/" + button.attr("data-project-id"),
							method: "DELETE",
							success: function () {
								table.row(button.closest("tr")).remove().draw();
							}
						});
					}
				});
			});

			$("#tasks").on("click", ".js-details", function () {
				var button = $(this);
				window.location.href = ("/Task/Details/" + button.attr("data-project-id"))
			});

			$("#tasks").on("click", ".js-add", function () {
			    var button = $(this);
				bootbox.confirm("Are you sure to add this task?", function (result) {
				    if (result) {
				        $.ajax({
				            url: "/api/tasks/gettask/" + button.attr("data-project-id"),
				            method: "GET",
				            success: function (task) {
				                $.ajax({
				                    url: "/api/tasks/modifyuser",
				                    method: "PUT",
                                    data: {tId : task.tId, t_uId : @Model.UserModel.UId},
				                    success: function () {
				                        bootbox.alert("Sikeres modositás");
				                    }
				                });
				            }
				        }).done(function () {
				            $.ajax({
				                url: "/api/tasks/gettask/" + button.attr("data-project-id"),
				                method: "GET",
				                success: function (gettask) {
				                    bootbox.alert("Az új user: " + gettask.t_uId );
				                }
				            });
				        });
					}
				});
			});
		});
	</script>
}

ProjectManagement/ProjectManagementLayer/Views/Task/TaskForm.cshtml
@model ProjectManagementLayer.ViewModels.TaskFormViewModel
@{
    ViewBag.Title = "New";
}

<h2>@ViewBag.Name</h2>
@* Ki kell még egésziteni a többi elemmel ami az új project létrehozásához kell *@
@using (Html.BeginForm("Save", "Task"))
{
    @Html.ValidationSummary(true, "Please fix the folowing errors.")
    <div class="form-group">
        @Html.LabelFor(m => m.TaskModel.TName)
        @Html.TextBoxFor(m => m.TaskModel.TName, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TaskModel.TName)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TaskModel.TComment)
        @Html.TextBoxFor(m => m.TaskModel.TComment, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TaskModel.TComment)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TaskModel.T_PId)
        @Html.DropDownListFor(m => m.TaskModel.T_PId, new SelectList(Model.ProjectModels, "PId", "PName"), "Select Task Maker", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TaskModel.T_PId)
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.TaskModel.TRequirement)
        @Html.DropDownListFor(m => m.TaskModel.TRequirement, new SelectList(Model.TaskList.Where(t => t.T_PId == Model.TaskModel.T_PId), "TId", "TName"), "Select Task Requirement", new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.TaskModel.TRequirement)
    </div>
    <div class="checkbox">
        <label>
            @Html.CheckBoxFor(m => m.TaskModel.TIsDone) Would you like to Archive it?
        </label>
    </div>
    @Html.HiddenFor(m => m.TaskModel.TId)
    @Html.HiddenFor(m => m.TaskModel.T_UId)
    @Html.AntiForgeryToken()
    <button type="submit" class="btn btn-primary">Save</button>
}

@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}